version: '3.8'

services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "9191:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: >
      sh -c "
      pip install -r /home/jovyan/work/requirements.txt &&
      start-notebook.sh --NotebookApp.token=''
      "
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daniil
      POSTGRES_PASSWORD: ovsyannikov
      POSTGRES_DB: runftwoods

volumes:
  pgdata:
EOF
